import React from "react";
/**
 * OverwriteCSS in Strapi Admin
 * Used as 'Icon'.
 */

const OverwriteCSS = () => {
  return (
    <React.Fragment>
      <style>
        {`
          /* Do not remove this selector */
          /* Hides overwriteCSS-Menu-Link */
          a[href^="/admin/only-overwrites-css"] {
            display: none;
          }

          /* Hides pabu plugin page until there's content */
          li a[href^="/admin/plugins/@am-gmbh/pabu-strapi-plugin"] {
            display: none;
          }

          /* Store */
          /* Hides autogenerated store fields (struuid & strname) */
          label[for="struuid"], label[for="struuid"] + div, input[id="struuid"] {
            display: none;
          }
          
          /* Currently not used: (relation dropdown label) */
          label[for="strname"], label[for="strname"] + div, input[id="strname"] {
            display: none;
          }

          /* List-Styling: contentElementSettings, store, cmsSettings, custom, global, pbemailsettings  */
          ol li ol li a[href*="/admin/content-manager/collection-types/plugin::pabu.cesstr"], 
          ol li ol li a[href*="/admin/content-manager/collection-types/plugin::pabu.str"], 
          ol li ol li a[href*="/admin/content-manager/single-types/plugin::pabu.pbcmssetting"], 
          ol li ol li a[href*="/admin/content-manager/single-types/plugin::pabu.custom"], 
          ol li ol li a[href*="/admin/content-manager/single-types/plugin::pabu.glbl"],
          ol li ol li a[href*="/admin/content-manager/single-types/plugin::pabu.pbemailsetting"] {
            background-color: #F2C500 !important;
          }

          ol li ol li a[href*="/admin/content-manager/collection-types/plugin::pabu.cesstr"].active, 
          ol li ol li a[href*="/admin/content-manager/collection-types/plugin::pabu.str"].active, 
          ol li ol li a[href*="/admin/content-manager/single-types/plugin::pabu.pbcmssetting"].active,
          ol li ol li a[href*="/admin/content-manager/single-types/plugin::pabu.custom"].active,
          ol li ol li a[href*="/admin/content-manager/single-types/plugin::pabu.glbl"].active,
          ol li ol li a[href*="/admin/content-manager/single-types/plugin::pabu.pbemailsetting"].active {
            border-right: 5px solid black;
          }

          ol li ol li a[href*="/admin/content-manager/collection-types/plugin::pabu.cesstr"].active span, 
          ol li ol li a[href*="/admin/content-manager/collection-types/plugin::pabu.str"].active span, 
          ol li ol li a[href*="/admin/content-manager/single-types/plugin::pabu.pbcmssetting"].active span,
          ol li ol li a[href*="/admin/content-manager/single-types/plugin::pabu.custom"].active span,
          ol li ol li a[href*="/admin/content-manager/single-types/plugin::pabu.glbl"].active span,
          ol li ol li a[href*="/admin/content-manager/single-types/plugin::pabu.pbemailsetting"].active span {
            color: black !important;
          }

          /* custom.css */
          textarea[aria-label="css input"], textarea[aria-label="tabletCss input"], textarea[aria-label="desktopCss input"], textarea[aria-label="wqhdCss input"] {
            height: min(22rem, 40vh);
          }

          /* global & cesstr enum-label adjustments */
          label[for="setting.0.titleHeading"]::after, label[for="setting.0.subheadlineheading"]::after, label[for="setting.0.headlineheading"]::after, label[for="footer.socialMediaTitleType"]::after {
            font-size: 0.75rem;
            white-space: nowrap;
            content: ' (HTML-Element Markup)';
            padding-left: 3px;
          }
          label[for="setting.0.alignmentX"]::after, label[for="setting.0.alignmentY"]::after {
            font-size: 0.75rem;
            white-space: nowrap;
            content: ' (caption-container)';
            padding-left: 3px;
          }

          /* Currently not used: */
          /* 
          label[for="setting.0.titleHeading"], label[for="setting.0.subheadlineheading"], label[for="setting.0.headlineheading"], label[for="footer.socialMediaTitleType"] {
            visibility: hidden;
            font-size: 0px;
          }
          */
          /*
          label[for="setting.0.titleHeading"]::after {
            content: 'titleHeading (HTML-Element Markup)';
          }
          label[for="setting.0.subheadlineheading"]::after {
            content: 'subheadlineHeading (HTML-Element Markup)';
          } 
          label[for="setting.0.headlineheading"]::after {
            content: 'headlineHeading (HTML-Element Markup)';
          }
          label[for="footer.socialMediaTitleType"]::after {
            content: 'socialMediaTitleType (HTML-Element Markup)';
          }
          */

        `}
      </style>
    </React.Fragment>
  );
};

export default OverwriteCSS;
